
name: likucs

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Find and Replace

        uses: jacobtomlinson/gha-find-replace@master

        with:

          find: "AsadSupport"

          replace: "Sakura_Music_Update"

      - name: Create Pull Request

        uses: stefanzweifel/git-auto-commit-action@v4

        with:

          commit_message: 'Replaced new name'

          commit_options: '--no-verify'

          repository: 'https://github.com/likucs/TGMusicBot'

          commit_user_name: likucs

          commit_user_email: likughost@gmail.com
